Repository ebizbase/nx, pull requests merged in 2024-11, with the labels that each got.

#2 feat(nx-docker): add build executor for build docker image
  .github/workflows/ci.yaml
  README.md
  e2e/main-spec/Dockerfile
  e2e/main-spec/project.json
  packages/nx-docker/README.md
  packages/nx-docker/eslint.config.js
  packages/nx-docker/executors.json
  packages/nx-docker/generators.json
  packages/nx-docker/jest.config.ts
  packages/nx-docker/package.json
  packages/nx-docker/project.json
  packages/nx-docker/src/executors/build/executor.spec.ts
  packages/nx-docker/src/executors/build/executor.ts
  packages/nx-docker/src/executors/build/schema.d.ts
  packages/nx-docker/src/executors/build/schema.json
  packages/nx-docker/src/index.ts
  packages/nx-docker/tsconfig.json
  packages/nx-docker/tsconfig.lib.json
  packages/nx-docker/tsconfig.spec.json
  release-config.json
  release-manifest.json
  tsconfig.base.json
Labels: size/m, pairing-wanted

#7 ci: fix ci report output
  .github/workflows/ci.yaml
Labels: size/xs

#10 chore: fix typo
  .github/pr-size.yaml
Labels: size/xs

#17 chore(release): release v1.0.0
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#19 chore(release): release v1.1.0
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#21 docs: update document
  README.md
  packages/nx-docker/README.md
  packages/nx-docker/package.json
Labels: size/m, pairing-wanted

#20 feat(nx-docker): add some options to nx docker build
  packages/nx-docker/src/executors/build/executor.spec.ts
  packages/nx-docker/src/executors/build/executor.ts
  packages/nx-docker/src/executors/build/schema.d.ts
  packages/nx-docker/src/executors/build/schema.json
Labels: size/s

#22 chore(release): release v1.2.0
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#26 chore(release): release nx-docker v1.3.0
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#30 feat(nx-docker): add option metadataFile and flatforms to build executor
  e2e/nx-docker-e2e/project.json
  packages/nx-docker/README.md
  packages/nx-docker/src/executors/build/executor.spec.ts
  packages/nx-docker/src/executors/build/executor.ts
  packages/nx-docker/src/executors/build/schema.d.ts
  packages/nx-docker/src/executors/build/schema.json
Labels: size/s

#31 chore(release): release nx-docker v1.4.0
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#44 chore(release): release nx-docker v1.4.1
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#45 chore(release): release nx-docker v1.4.2
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending

#46 chore(release): release nx-docker v1.4.3
  packages/nx-docker/CHANGELOG.md
  packages/nx-docker/package.json
  release-manifest.json
Labels: autorelease: pending
